-- ============================================================
-- KABOOM PRODUCTION SCHEMA v2.0
-- Complete, verified, aligned with backend code
-- Generated by Phase 4 Supabase Certification
-- ============================================================
-- INSTRUCTIONS:
-- 1. Open Supabase SQL Editor
-- 2. First run the permissions fix (Step 1 below)
-- 3. Then run the schema additions (Step 2 below)
-- DO NOT drop the existing schema. This is ADDITIVE.
-- ============================================================

-- ============================================================
-- STEP 1: RESTORE PERMISSIONS (RUN FIRST)
-- ============================================================

GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres, anon, authenticated, service_role;

-- ============================================================
-- STEP 2: ADD MISSING COLUMNS TO EXISTING TABLES
-- ============================================================

-- 2a. visitor_sessions: Add match_id column
-- Referenced by: heartbeat sync guardrail (routes/index.ts L134, L163)
ALTER TABLE visitor_sessions ADD COLUMN IF NOT EXISTS match_id UUID REFERENCES matches(id) ON DELETE SET NULL;
ALTER TABLE visitor_sessions ADD COLUMN IF NOT EXISTS user_state VARCHAR(50);
CREATE INDEX IF NOT EXISTS idx_visitor_sessions_match_id ON visitor_sessions(match_id);

-- 2b. waiting_queue: Add last_seen column
-- Referenced by: queueEngine.ts L78, L114 (heartbeat tracking)
ALTER TABLE waiting_queue ADD COLUMN IF NOT EXISTS last_seen TIMESTAMPTZ DEFAULT NOW();

-- 2c. matches: Add scoring, readiness, and like tracking columns
-- Referenced by: matchingEngine.ts L641-652 (match creation)
--                matchingEngine.ts L321 (heal cycle media timeout)
--                routes/index.ts L580-592 (like tracking)
ALTER TABLE matches ADD COLUMN IF NOT EXISTS match_score REAL;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS matched_reason VARCHAR(100);
ALTER TABLE matches ADD COLUMN IF NOT EXISTS match_reason_metadata JSONB DEFAULT '{}'::jsonb;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS user_a_ready BOOLEAN DEFAULT false;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS user_b_ready BOOLEAN DEFAULT false;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS negotiation_started BOOLEAN DEFAULT false;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS user_a_media_ready BOOLEAN DEFAULT false;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS user_b_media_ready BOOLEAN DEFAULT false;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS liked_by_a BOOLEAN DEFAULT false;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS liked_by_b BOOLEAN DEFAULT false;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'active';

-- 2d. temporary_messages: Add sender_session, message, expires_at
-- The schema has sender_id and content, but code uses sender_session and message
-- We add the code-expected columns alongside the schema ones
ALTER TABLE temporary_messages ADD COLUMN IF NOT EXISTS sender_session UUID REFERENCES visitor_sessions(id) ON DELETE CASCADE;
ALTER TABLE temporary_messages ADD COLUMN IF NOT EXISTS message TEXT;
ALTER TABLE temporary_messages ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;
-- Make content nullable since code uses 'message' instead
ALTER TABLE temporary_messages ALTER COLUMN content DROP NOT NULL;

-- 2e. reservations: Restructure for matchmaker reservation pattern
-- Code expects initiator_session_id + partner_session_id + expires_at
-- Schema has match_id (NOT NULL) + session_id which is incompatible
-- We need to make match_id nullable (reservation is created BEFORE the match)
-- and add the initiator/partner columns
ALTER TABLE reservations ALTER COLUMN match_id DROP NOT NULL;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS initiator_session_id UUID REFERENCES visitor_sessions(id) ON DELETE CASCADE;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS partner_session_id UUID REFERENCES visitor_sessions(id) ON DELETE CASCADE;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;
CREATE INDEX IF NOT EXISTS idx_reservations_initiator ON reservations(initiator_session_id);
CREATE INDEX IF NOT EXISTS idx_reservations_partner ON reservations(partner_session_id);
CREATE INDEX IF NOT EXISTS idx_reservations_status ON reservations(status);
CREATE INDEX IF NOT EXISTS idx_reservations_expires ON reservations(expires_at);

-- 2f. analytics_events: Add match_id and idempotency_key
-- Referenced by: analytics/logger.ts
ALTER TABLE analytics_events ADD COLUMN IF NOT EXISTS match_id UUID REFERENCES matches(id) ON DELETE SET NULL;
ALTER TABLE analytics_events ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(255);
CREATE UNIQUE INDEX IF NOT EXISTS idx_analytics_events_idempotency ON analytics_events(idempotency_key) WHERE idempotency_key IS NOT NULL;

-- ============================================================
-- STEP 3: CREATE MISSING TABLES
-- ============================================================

-- 3a. locations table
-- Referenced by: GET /api/locations (routes/index.ts L486)
CREATE TABLE IF NOT EXISTS locations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(255) NOT NULL,
  state VARCHAR(100),
  country VARCHAR(100) DEFAULT 'India',
  type VARCHAR(50) DEFAULT 'city',
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_locations_name ON locations(name);

-- 3b. interests table
-- Referenced by: GET /api/interests (routes/index.ts L527)
CREATE TABLE IF NOT EXISTS interests (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(255) NOT NULL UNIQUE,
  category VARCHAR(100),
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_interests_name ON interests(name);

-- 3c. likes table
-- Referenced by: POST /api/like (routes/index.ts L576)
CREATE TABLE IF NOT EXISTS likes (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  match_id UUID NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  session_id UUID NOT NULL REFERENCES visitor_sessions(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(match_id, session_id)
);
CREATE INDEX IF NOT EXISTS idx_likes_match ON likes(match_id);
CREATE INDEX IF NOT EXISTS idx_likes_session ON likes(session_id);

-- 3d. matchmaker_metrics (singleton table for global matchmaker stats)
-- Referenced by: repositories/index.ts L340 (getGlobalMatchmakerMetrics)
CREATE TABLE IF NOT EXISTS matchmaker_metrics (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  total_searching_users INTEGER DEFAULT 0,
  average_wait_time REAL DEFAULT 0,
  maximum_wait_time REAL DEFAULT 0,
  successful_matches INTEGER DEFAULT 0,
  failed_matches INTEGER DEFAULT 0,
  rematches INTEGER DEFAULT 0,
  abandoned_searches INTEGER DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
-- Insert the singleton row
INSERT INTO matchmaker_metrics (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- 3e. analytics_sync_state (ETL checkpoint tracking)
-- Referenced by: etlService.ts L12
CREATE TABLE IF NOT EXISTS analytics_sync_state (
  job_name VARCHAR(100) PRIMARY KEY,
  last_processed_timestamp TIMESTAMPTZ DEFAULT '2000-01-01T00:00:00Z',
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3f. dashboard_summary: Fix schema to match code expectations
-- Code expects integer id=1 and columns: total_visitors, queue_joins, etc.
-- Current schema has UUID id and different columns.
-- Strategy: Drop the existing broken table and recreate correctly.
DROP TABLE IF EXISTS dashboard_summary CASCADE;
CREATE TABLE dashboard_summary (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  total_visitors INTEGER DEFAULT 0,
  queue_joins INTEGER DEFAULT 0,
  matches_created INTEGER DEFAULT 0,
  connected_calls INTEGER DEFAULT 0,
  mutual_likes INTEGER DEFAULT 0,
  avg_wait_seconds INTEGER DEFAULT 0,
  avg_duration_seconds INTEGER DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
INSERT INTO dashboard_summary (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- 3g. dashboard_match_analytics (funnel metrics)
-- Referenced by: etlService.ts L59, analytics/service.ts L27
CREATE TABLE IF NOT EXISTS dashboard_match_analytics (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  queue_joins INTEGER DEFAULT 0,
  matched INTEGER DEFAULT 0,
  connected INTEGER DEFAULT 0,
  completed INTEGER DEFAULT 0,
  liked INTEGER DEFAULT 0,
  mutual_likes INTEGER DEFAULT 0,
  skipped_count INTEGER DEFAULT 0,
  partner_left_count INTEGER DEFAULT 0,
  timeout_count INTEGER DEFAULT 0,
  failed_negotiation_count INTEGER DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
INSERT INTO dashboard_match_analytics (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- 3h. dashboard_rankings (geographic/device rankings)
-- Referenced by: etlService.ts L201, analytics/service.ts L22
CREATE TABLE IF NOT EXISTS dashboard_rankings (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  category VARCHAR(50) NOT NULL,
  label VARCHAR(255) NOT NULL,
  count INTEGER DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(category, label)
);
CREATE INDEX IF NOT EXISTS idx_rankings_category ON dashboard_rankings(category);
CREATE INDEX IF NOT EXISTS idx_rankings_count ON dashboard_rankings(count DESC);

-- 3i. dashboard_hourly (time series: hourly aggregation)
-- Referenced by: etlService.ts L210, analytics/service.ts L12
CREATE TABLE IF NOT EXISTS dashboard_hourly (
  hour_timestamp TIMESTAMPTZ PRIMARY KEY,
  visitors INTEGER DEFAULT 0,
  queue_joins INTEGER DEFAULT 0,
  connections INTEGER DEFAULT 0,
  total_wait_seconds INTEGER DEFAULT 0,
  total_duration_seconds INTEGER DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3j. dashboard_daily (time series: daily aggregation)
-- Referenced by: etlService.ts L224, analytics/service.ts L13
CREATE TABLE IF NOT EXISTS dashboard_daily (
  date_timestamp DATE PRIMARY KEY,
  visitors INTEGER DEFAULT 0,
  queue_joins INTEGER DEFAULT 0,
  connections INTEGER DEFAULT 0,
  total_wait_seconds INTEGER DEFAULT 0,
  total_duration_seconds INTEGER DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3k. dashboard_activity (recent activity feed)
-- Referenced by: etlService.ts L238, analytics/service.ts L37
CREATE TABLE IF NOT EXISTS dashboard_activity (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  event_type VARCHAR(50) NOT NULL,
  session_id UUID REFERENCES visitor_sessions(id) ON DELETE SET NULL,
  payload JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_activity_created ON dashboard_activity(created_at DESC);

-- 3l. dashboard_notifications (notification analytics summary)
-- Referenced by: analytics/service.ts L32
CREATE TABLE IF NOT EXISTS dashboard_notifications (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  total_sent INTEGER DEFAULT 0,
  total_clicked INTEGER DEFAULT 0,
  total_subscriptions INTEGER DEFAULT 0,
  ctr REAL DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
INSERT INTO dashboard_notifications (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- STEP 4: CREATE MISSING RPCs (Functions)
-- ============================================================

-- 4a. matchmaker_create_reservation
-- Atomically creates a reservation for two sessions
-- Referenced by: reservationEngine.ts L25
CREATE OR REPLACE FUNCTION matchmaker_create_reservation(
  p_initiator_id UUID,
  p_partner_id UUID,
  p_expires_at TIMESTAMPTZ
)
RETURNS UUID
LANGUAGE plpgsql
AS $$
DECLARE
  v_reservation_id UUID;
BEGIN
  -- Check neither user is already reserved
  IF EXISTS (
    SELECT 1 FROM reservations
    WHERE (initiator_session_id = p_initiator_id OR partner_session_id = p_initiator_id
           OR initiator_session_id = p_partner_id OR partner_session_id = p_partner_id)
    AND status = 'pending'
  ) THEN
    RAISE EXCEPTION 'One or both users already have a pending reservation';
  END IF;

  -- Lock both sessions to RESERVED
  UPDATE visitor_sessions SET status = 'RESERVED', last_activity = NOW()
  WHERE id IN (p_initiator_id, p_partner_id)
  AND status = 'SEARCHING';

  -- Create reservation row
  INSERT INTO reservations (initiator_session_id, partner_session_id, status, expires_at)
  VALUES (p_initiator_id, p_partner_id, 'pending', p_expires_at)
  RETURNING id INTO v_reservation_id;

  RETURN v_reservation_id;
END;
$$;

-- 4b. matchmaker_heal_cycle
-- Cleans up expired reservations and orphaned states
-- Referenced by: matchingEngine.ts L313
CREATE OR REPLACE FUNCTION matchmaker_heal_cycle()
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_now TIMESTAMPTZ := NOW();
BEGIN
  -- Expire stale reservations past their expiry time
  UPDATE reservations SET status = 'expired'
  WHERE status = 'pending' AND expires_at < v_now;

  -- Reset sessions stuck in RESERVED with no active reservation
  UPDATE visitor_sessions SET status = 'SEARCHING', last_activity = v_now
  WHERE status = 'RESERVED'
  AND id NOT IN (
    SELECT initiator_session_id FROM reservations WHERE status = 'pending'
    UNION
    SELECT partner_session_id FROM reservations WHERE status = 'pending'
  );
END;
$$;

-- 4c. update_matchmaker_metrics
-- Upserts global matchmaker metrics (singleton row)
-- Referenced by: repositories/index.ts L324
CREATE OR REPLACE FUNCTION update_matchmaker_metrics(
  p_total_searching_users INTEGER,
  p_avg_wait REAL,
  p_max_wait REAL,
  p_succ INTEGER,
  p_fail INTEGER,
  p_rematches INTEGER,
  p_abandoned INTEGER
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO matchmaker_metrics (id, total_searching_users, average_wait_time, maximum_wait_time,
    successful_matches, failed_matches, rematches, abandoned_searches, updated_at)
  VALUES (1, p_total_searching_users, p_avg_wait, p_max_wait,
    p_succ, p_fail, p_rematches, p_abandoned, NOW())
  ON CONFLICT (id) DO UPDATE SET
    total_searching_users = p_total_searching_users,
    average_wait_time = p_avg_wait,
    maximum_wait_time = p_max_wait,
    successful_matches = matchmaker_metrics.successful_matches + p_succ,
    failed_matches = matchmaker_metrics.failed_matches + p_fail,
    rematches = matchmaker_metrics.rematches + p_rematches,
    abandoned_searches = matchmaker_metrics.abandoned_searches + p_abandoned,
    updated_at = NOW();
END;
$$;

-- ============================================================
-- STEP 5: RLS & PERMISSIONS FOR NEW TABLES
-- ============================================================

ALTER TABLE locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE interests ENABLE ROW LEVEL SECURITY;
ALTER TABLE likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE matchmaker_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE analytics_sync_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE dashboard_summary ENABLE ROW LEVEL SECURITY;
ALTER TABLE dashboard_match_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE dashboard_rankings ENABLE ROW LEVEL SECURITY;
ALTER TABLE dashboard_hourly ENABLE ROW LEVEL SECURITY;
ALTER TABLE dashboard_daily ENABLE ROW LEVEL SECURITY;
ALTER TABLE dashboard_activity ENABLE ROW LEVEL SECURITY;
ALTER TABLE dashboard_notifications ENABLE ROW LEVEL SECURITY;

-- Deny public/anon direct access (backend uses service_role which bypasses RLS)
CREATE POLICY "Deny public access" ON locations FOR ALL USING (false);
CREATE POLICY "Deny public access" ON interests FOR ALL USING (false);
CREATE POLICY "Deny public access" ON likes FOR ALL USING (false);
CREATE POLICY "Deny public access" ON matchmaker_metrics FOR ALL USING (false);
CREATE POLICY "Deny public access" ON analytics_sync_state FOR ALL USING (false);
CREATE POLICY "Deny public access" ON dashboard_match_analytics FOR ALL USING (false);
CREATE POLICY "Deny public access" ON dashboard_rankings FOR ALL USING (false);
CREATE POLICY "Deny public access" ON dashboard_hourly FOR ALL USING (false);
CREATE POLICY "Deny public access" ON dashboard_daily FOR ALL USING (false);
CREATE POLICY "Deny public access" ON dashboard_activity FOR ALL USING (false);
CREATE POLICY "Deny public access" ON dashboard_notifications FOR ALL USING (false);

-- Re-grant permissions to service_role on ALL tables (including new ones)
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;

-- ============================================================
-- STEP 6: SEED DATA FOR LOCATIONS AND INTERESTS
-- ============================================================

-- Seed some initial Indian locations for autocomplete
INSERT INTO locations (name, state, country, type) VALUES
  ('Hyderabad', 'Telangana', 'India', 'city'),
  ('Bangalore', 'Karnataka', 'India', 'city'),
  ('Mumbai', 'Maharashtra', 'India', 'city'),
  ('Delhi', 'Delhi', 'India', 'city'),
  ('Chennai', 'Tamil Nadu', 'India', 'city'),
  ('Kolkata', 'West Bengal', 'India', 'city'),
  ('Pune', 'Maharashtra', 'India', 'city'),
  ('Ahmedabad', 'Gujarat', 'India', 'city'),
  ('Jaipur', 'Rajasthan', 'India', 'city'),
  ('Lucknow', 'Uttar Pradesh', 'India', 'city'),
  ('Kochi', 'Kerala', 'India', 'city'),
  ('Chandigarh', 'Punjab', 'India', 'city'),
  ('Indore', 'Madhya Pradesh', 'India', 'city'),
  ('Bhopal', 'Madhya Pradesh', 'India', 'city'),
  ('Visakhapatnam', 'Andhra Pradesh', 'India', 'city'),
  ('Coimbatore', 'Tamil Nadu', 'India', 'city'),
  ('Nagpur', 'Maharashtra', 'India', 'city'),
  ('Patna', 'Bihar', 'India', 'city'),
  ('Bhubaneswar', 'Odisha', 'India', 'city'),
  ('Thiruvananthapuram', 'Kerala', 'India', 'city'),
  ('Guwahati', 'Assam', 'India', 'city'),
  ('Noida', 'Uttar Pradesh', 'India', 'city'),
  ('Gurgaon', 'Haryana', 'India', 'city'),
  ('Surat', 'Gujarat', 'India', 'city'),
  ('Vadodara', 'Gujarat', 'India', 'city'),
  ('Mysore', 'Karnataka', 'India', 'city'),
  ('Mangalore', 'Karnataka', 'India', 'city'),
  ('Dehradun', 'Uttarakhand', 'India', 'city'),
  ('Ranchi', 'Jharkhand', 'India', 'city'),
  ('Raipur', 'Chhattisgarh', 'India', 'city')
ON CONFLICT DO NOTHING;

-- Seed some interests for autocomplete
INSERT INTO interests (name, category) VALUES
  ('Gaming', 'Entertainment'),
  ('Music', 'Entertainment'),
  ('Movies', 'Entertainment'),
  ('Anime', 'Entertainment'),
  ('Reading', 'Education'),
  ('Coding', 'Technology'),
  ('Sports', 'Fitness'),
  ('Cricket', 'Sports'),
  ('Football', 'Sports'),
  ('Travel', 'Lifestyle'),
  ('Photography', 'Creative'),
  ('Art', 'Creative'),
  ('Dancing', 'Creative'),
  ('Cooking', 'Lifestyle'),
  ('Fitness', 'Health'),
  ('Yoga', 'Health'),
  ('Fashion', 'Lifestyle'),
  ('Startups', 'Business'),
  ('Finance', 'Business'),
  ('Science', 'Education'),
  ('Philosophy', 'Education'),
  ('Politics', 'Social'),
  ('Memes', 'Entertainment'),
  ('K-Pop', 'Music'),
  ('Bollywood', 'Entertainment'),
  ('Stand-up Comedy', 'Entertainment'),
  ('Astronomy', 'Science'),
  ('Psychology', 'Education'),
  ('Volunteering', 'Social'),
  ('Pets', 'Lifestyle')
ON CONFLICT DO NOTHING;

-- ============================================================
-- STEP 7: ENABLE TRIGRAM EXTENSION (for ILIKE performance)
-- ============================================================
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ============================================================
-- VERIFICATION QUERY: Run this to confirm everything was created
-- ============================================================
-- SELECT table_name FROM information_schema.tables
-- WHERE table_schema = 'public' ORDER BY table_name;
--
-- Expected: 24 tables total
-- analytics_events, analytics_sync_state, connection_logs,
-- dashboard_activity, dashboard_daily, dashboard_hourly,
-- dashboard_match_analytics, dashboard_notifications,
-- dashboard_rankings, dashboard_summary, feedback, interests,
-- likes, locations, matchmaker_metrics, matches,
-- push_subscriptions, reports, reservations, server_metrics,
-- temporary_messages, user_preferences_cache, visitor_sessions,
-- waiting_queue
