name = "indiatv-backend"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"
SUPABASE_URL = "https://dirocenpssdilkztizps.supabase.co"

[triggers]
crons = ["* * * * *"]
